import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { supabase } from '../lib/supabase';
import type { UserProfile, UserProgress } from '../engine/types';

interface AuthStore {
  user: UserProfile | null;
  progress: UserProgress | null;
  isLoading: boolean;
  isAuthenticated: boolean;
  needsUsername: boolean; // True when Google user needs to set username

  // Actions
  signIn: (email: string, password: string) => Promise<{ error?: string }>;
  signUp: (email: string, password: string, username: string) => Promise<{ error?: string }>;
  signInWithGoogle: () => Promise<{ error?: string }>;
  signOut: () => Promise<void>;
  fetchProfile: () => Promise<void>;
  fetchProgress: () => Promise<void>;
  updateProgress: (progress: Partial<UserProgress>) => Promise<void>;
  setUsername: (username: string) => Promise<{ error?: string }>;
  addClassicStars: (stars: number) => Promise<void>;
  updateHardestPuzzle: (stars: number) => Promise<void>;
}

export const useAuthStore = create<AuthStore>()(
  persist(
    (set, get) => ({
      user: null,
      progress: null,
      isLoading: true,
      isAuthenticated: false,
      needsUsername: false,

      signIn: async (email: string, password: string) => {
        try {
          const { error } = await supabase.auth.signInWithPassword({
            email,
            password,
          });

          if (error) {
            return { error: error.message };
          }

          await get().fetchProfile();
          await get().fetchProgress();
          return {};
        } catch {
          return { error: 'An unexpected error occurred' };
        }
      },

      signUp: async (email: string, password: string, username: string) => {
        try {
          const { data, error } = await supabase.auth.signUp({
            email,
            password,
            options: {
              data: { username },
            },
          });

          if (error) {
            return { error: error.message };
          }

          if (data.user) {
            // Profile will be created by database trigger
            await get().fetchProfile();
          }

          return {};
        } catch {
          return { error: 'An unexpected error occurred' };
        }
      },

      signInWithGoogle: async () => {
        try {
          // Use the full URL including path (e.g., /robozzle/ for GitHub Pages)
          const baseUrl = window.location.origin + window.location.pathname;
          // Remove trailing hash or query params, ensure it ends with /
          const redirectUrl = baseUrl.split('#')[0].split('?')[0].replace(/\/$/, '') + '/';

          const { error } = await supabase.auth.signInWithOAuth({
            provider: 'google',
            options: {
              redirectTo: redirectUrl,
            },
          });

          if (error) {
            return { error: error.message };
          }

          return {};
        } catch {
          return { error: 'An unexpected error occurred' };
        }
      },

      signOut: async () => {
        await supabase.auth.signOut();
        set({ user: null, progress: null, isAuthenticated: false, needsUsername: false });
      },

      fetchProfile: async () => {
        try {
          const { data: { user } } = await supabase.auth.getUser();

          if (!user) {
            set({ user: null, isAuthenticated: false, isLoading: false, needsUsername: false });
            return;
          }

          const { data: profile } = await supabase
            .from('profiles')
            .select('*')
            .eq('id', user.id)
            .maybeSingle();

          if (profile) {
            // Check if this is a Google user without a proper username
            // Google users get auto-generated usernames like "user_abc123" from the trigger
            const isAutoGeneratedUsername = profile.username?.startsWith('user_') || !profile.username;
            const isGoogleUser = user.app_metadata?.provider === 'google';

            if (isGoogleUser && isAutoGeneratedUsername) {
              // User needs to set a username
              set({
                user: null,
                isAuthenticated: false,
                isLoading: false,
                needsUsername: true,
              });
            } else {
              set({
                user: {
                  id: profile.id,
                  username: profile.username,
                  email: user.email || '',
                  role: profile.role || null,
                  puzzlesSolved: profile.puzzles_solved,
                  currentStreak: profile.current_streak,
                  longestStreak: profile.longest_streak,
                  totalPoints: profile.total_points,
                  classicStars: profile.classic_stars || 0,
                  hardestPuzzleStars: profile.hardest_puzzle_stars || 0,
                  bestDailyEasyRank: profile.best_daily_easy_rank,
                  bestDailyChallengeRank: profile.best_daily_challenge_rank,
                  lastDailyDate: profile.last_daily_date,
                  createdAt: new Date(profile.created_at),
                },
                isAuthenticated: true,
                isLoading: false,
                needsUsername: false,
              });
            }
          } else {
            // No profile yet - if Google user, they need to create username
            const isGoogleUser = user.app_metadata?.provider === 'google';
            set({
              isLoading: false,
              needsUsername: isGoogleUser,
            });
          }
        } catch (err) {
          console.error('Error fetching profile:', err);
          set({ isLoading: false });
        }
      },

      fetchProgress: async () => {
        try {
          const { data: { user } } = await supabase.auth.getUser();

          if (!user) return;

          const { data: progress } = await supabase
            .from('user_progress')
            .select('*')
            .eq('user_id', user.id)
            .maybeSingle();

          if (progress) {
            set({
              progress: {
                tutorialCompleted: progress.tutorial_completed || [],
                classicSolved: progress.classic_solved || [],
                dailySolved: progress.daily_solved || [],
              },
            });
          }
        } catch (err) {
          console.error('Error fetching progress:', err);
        }
      },

      setUsername: async (username: string) => {
        try {
          const { data: { user } } = await supabase.auth.getUser();

          if (!user) {
            return { error: 'Not authenticated' };
          }

          // Check if username is already taken
          const { data: existing } = await supabase
            .from('profiles')
            .select('id')
            .eq('username', username)
            .neq('id', user.id)
            .maybeSingle();

          if (existing) {
            return { error: 'Username is already taken' };
          }

          // Update or create the profile with the new username
          const { error } = await supabase
            .from('profiles')
            .upsert({
              id: user.id,
              username: username,
            });

          if (error) {
            return { error: error.message };
          }

          // Fetch the updated profile
          set({ needsUsername: false });
          await get().fetchProfile();
          await get().fetchProgress();

          return {};
        } catch (err) {
          console.error('Error setting username:', err);
          return { error: 'An unexpected error occurred' };
        }
      },

      updateProgress: async (newProgress: Partial<UserProgress>) => {
        try {
          const { progress } = get();

          // Merge new progress with existing progress
          const mergedProgress: UserProgress = {
            tutorialCompleted: newProgress.tutorialCompleted || progress?.tutorialCompleted || [],
            classicSolved: newProgress.classicSolved || progress?.classicSolved || [],
            dailySolved: newProgress.dailySolved || progress?.dailySolved || [],
          };

          // Always update local state (this gets persisted via zustand persist)
          set({ progress: mergedProgress });

          // If authenticated, also save to Supabase
          const { data: { user } } = await supabase.auth.getUser();
          if (user) {
            await supabase
              .from('user_progress')
              .upsert({
                user_id: user.id,
                tutorial_completed: mergedProgress.tutorialCompleted,
                classic_solved: mergedProgress.classicSolved,
                daily_solved: mergedProgress.dailySolved,
              }, { onConflict: 'user_id' });
          }
        } catch (err) {
          console.error('Error updating progress:', err);
        }
      },

      addClassicStars: async (stars: number) => {
        try {
          const { user } = get();
          if (!user) return;

          const newStars = (user.classicStars || 0) + stars;

          // Update local state
          set({
            user: {
              ...user,
              classicStars: newStars,
            },
          });

          // Update in Supabase
          const { data: { user: authUser } } = await supabase.auth.getUser();
          if (authUser) {
            await supabase
              .from('profiles')
              .update({ classic_stars: newStars })
              .eq('id', authUser.id);
          }
        } catch (err) {
          console.error('Error updating classic stars:', err);
        }
      },

      updateHardestPuzzle: async (stars: number) => {
        try {
          const { user } = get();
          if (!user) return;

          // Only update if this puzzle is harder than previous hardest
          if (stars <= (user.hardestPuzzleStars || 0)) return;

          // Update local state
          set({
            user: {
              ...user,
              hardestPuzzleStars: stars,
            },
          });

          // Update in Supabase
          const { data: { user: authUser } } = await supabase.auth.getUser();
          if (authUser) {
            await supabase
              .from('profiles')
              .update({ hardest_puzzle_stars: stars })
              .eq('id', authUser.id);
          }
        } catch (err) {
          console.error('Error updating hardest puzzle:', err);
        }
      },
    }),
    {
      name: 'robozzle-auth',
      partialize: (state) => ({
        // Only persist these fields
        user: state.user,
        progress: state.progress,
      }),
    }
  )
);

// Initialize auth state listener
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_IN' && session) {
    useAuthStore.getState().fetchProfile();
    useAuthStore.getState().fetchProgress();
  } else if (event === 'SIGNED_OUT') {
    useAuthStore.setState({ user: null, progress: null, isAuthenticated: false });
  }
});
